Cria rota de API para criar ou atualizar uma lista de cards
Sysvale/board pull request #167
Opened 2024-01-19 14:27 UTC by carloslamark

- Adiciona rota de API `/cards/update-or-create` para atualizar uma lista de cards, no formato:
```
{
    [
        "title": "Card criado via api", // titulo do card
	"type":  "user-story", // tipo do card. para mais tipos ver: App/Constants/CardTypes
	"board_list_id" : "645259f8ec05ef07130f31a8", // id da lista onde o card será criado
	"user_story_id": "6458e1a8a90d9a6e0e697d02", // opcional, deve ser enviado quando o card criado é do tipo task
        "integration_metadata": [
             "granatum": [ // nome da aplicação
                  "id": "1231y54kh3khiu1g23uh6" // id do elemento atrelado ao card
              ]
         ]
    ],
}
```

2024-01-23 17:09 UTC, tassiocaique requested changes

2024-01-23 17:09 UTC, tassiocaique commented on app/Http/Controllers/CardController.php
> +			$key = key($card['integration_metadata']);
Acho que essa questão da chave pode ser implementada de uma maneira mais escalável. Da maneira atual, está muito restrita ao `integration_metadata`. Você pode, por exemplo, mandar no corpo da requisição - além da lista de cards a ser atualizada/criada - um parâmetro que especifica qual a chave vai ser analisada para verificar a existência do item no banco de dados. Assim, você não torna a implementação muito restritiva à um campo específico, tornando a utilização da API mais flexível e escalável.

2024-01-23 17:09 UTC, tassiocaique commented on API.md
> +    "number": 1,
Interssante observar quais dados são estritamente necessários nessa requisição. Não acredito que seja necessário enviar, por exemplo, o `number` e o `created_at`. Lembre-se que é uma requisição em lote e quanto menos dados trafegarmos melhor tende a ser a performance.

2024-01-23 17:09 UTC, tassiocaique commented on API.md
> +##### Response: Array dos Cards
Acredito que aqui você esteja descrevendo uma `Request` e não uma `Response`

2024-01-24 13:46 UTC, carloslamark commented on routes/api.php
> +Route::put('cards/update-or-create', [CardController::class, 'updateOrCreate'])
feito

2024-01-24 13:46 UTC, carloslamark commented on routes/api.php
> +	->name('api.cards.updateOrCreate');
feito

2024-01-24 13:47 UTC, carloslamark commented on API.md
> +##### Response: Array dos Cards
feito

2024-01-24 13:59 UTC, carloslamark commented on app/Http/Controllers/CardController.php
> +			$key = key($card['integration_metadata']);
feito

2024-01-25 11:52 UTC, tassiocaique commented on API.md
> +	"batch_key" => "integration_metadata.granatum", // chave do id do elemento atrelado ao card, deve ser uma string
Eu prefiro que seja uma coisa mais semântica, tipo `update_attribute` ou `update_attribute_criteria`, algo do gênero. E além disso, que ele seja o mais "modular" possível. Nesse teu exemplo, ao invés de vc passar o `integration_metadata.granatum` ser o `integration_metadata.granatum.id`.

2024-01-25 11:57 UTC, carloslamark commented on API.md
> +	"batch_key" => "integration_metadata.granatum", // chave do id do elemento atrelado ao card, deve ser uma string
Realmente, passando ele inteiro fica bem mais flexível. Vou mudar

2024-01-25 12:12 UTC, tassiocaique commented on API.md
> +	"update_attribute" => "integration_metadata.granatum.id", // chave do id do elemento atrelado ao card, deve ser uma string
```suggestion
	"update_attribute" => "integration_metadata.granatum.id", // atributo que será utilizado como critério para verificar a existência do elemento (caso exista, será atualizado. Caso não, será criado)
```

2024-01-25 12:18 UTC, tassiocaique approved these changes

2024-01-25 12:21 UTC, merged